package com.entity;

import java.util.Date;

public class AcceptDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.dealmanagerid
     *
     * @mbggenerated
     */
    private Integer dealmanagerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.dealview
     *
     * @mbggenerated
     */
    private String dealview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_accept.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.id
     *
     * @return the value of d_accept.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.id
     *
     * @param id the value for d_accept.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.dealmanagerid
     *
     * @return the value of d_accept.dealmanagerid
     *
     * @mbggenerated
     */
    public Integer getDealmanagerid() {
        return dealmanagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.dealmanagerid
     *
     * @param dealmanagerid the value for d_accept.dealmanagerid
     *
     * @mbggenerated
     */
    public void setDealmanagerid(Integer dealmanagerid) {
        this.dealmanagerid = dealmanagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.dealview
     *
     * @return the value of d_accept.dealview
     *
     * @mbggenerated
     */
    public String getDealview() {
        return dealview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.dealview
     *
     * @param dealview the value for d_accept.dealview
     *
     * @mbggenerated
     */
    public void setDealview(String dealview) {
        this.dealview = dealview == null ? null : dealview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.status
     *
     * @return the value of d_accept.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.status
     *
     * @param status the value for d_accept.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.createtime
     *
     * @return the value of d_accept.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.createtime
     *
     * @param createtime the value for d_accept.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_accept.updatetime
     *
     * @return the value of d_accept.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_accept.updatetime
     *
     * @param updatetime the value for d_accept.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}