package com.entity;

import java.util.Date;

public class HouseDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.numOfCertificate
     *
     * @mbggenerated
     */
    private String numofcertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.years
     *
     * @mbggenerated
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.marketValue
     *
     * @mbggenerated
     */
    private Float marketvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.valueOfArround
     *
     * @mbggenerated
     */
    private Float valueofarround;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.city
     *
     * @mbggenerated
     */
    private Float city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.houseType
     *
     * @mbggenerated
     */
    private String housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.payment
     *
     * @mbggenerated
     */
    private Float payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.area
     *
     * @mbggenerated
     */
    private Float area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_house.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.id
     *
     * @return the value of d_house.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.id
     *
     * @param id the value for d_house.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.user_id
     *
     * @return the value of d_house.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.user_id
     *
     * @param userId the value for d_house.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.numOfCertificate
     *
     * @return the value of d_house.numOfCertificate
     *
     * @mbggenerated
     */
    public String getNumofcertificate() {
        return numofcertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.numOfCertificate
     *
     * @param numofcertificate the value for d_house.numOfCertificate
     *
     * @mbggenerated
     */
    public void setNumofcertificate(String numofcertificate) {
        this.numofcertificate = numofcertificate == null ? null : numofcertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.price
     *
     * @return the value of d_house.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.price
     *
     * @param price the value for d_house.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.years
     *
     * @return the value of d_house.years
     *
     * @mbggenerated
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.years
     *
     * @param years the value for d_house.years
     *
     * @mbggenerated
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.marketValue
     *
     * @return the value of d_house.marketValue
     *
     * @mbggenerated
     */
    public Float getMarketvalue() {
        return marketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.marketValue
     *
     * @param marketvalue the value for d_house.marketValue
     *
     * @mbggenerated
     */
    public void setMarketvalue(Float marketvalue) {
        this.marketvalue = marketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.valueOfArround
     *
     * @return the value of d_house.valueOfArround
     *
     * @mbggenerated
     */
    public Float getValueofarround() {
        return valueofarround;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.valueOfArround
     *
     * @param valueofarround the value for d_house.valueOfArround
     *
     * @mbggenerated
     */
    public void setValueofarround(Float valueofarround) {
        this.valueofarround = valueofarround;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.city
     *
     * @return the value of d_house.city
     *
     * @mbggenerated
     */
    public Float getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.city
     *
     * @param city the value for d_house.city
     *
     * @mbggenerated
     */
    public void setCity(Float city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.houseType
     *
     * @return the value of d_house.houseType
     *
     * @mbggenerated
     */
    public String getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.houseType
     *
     * @param housetype the value for d_house.houseType
     *
     * @mbggenerated
     */
    public void setHousetype(String housetype) {
        this.housetype = housetype == null ? null : housetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.payment
     *
     * @return the value of d_house.payment
     *
     * @mbggenerated
     */
    public Float getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.payment
     *
     * @param payment the value for d_house.payment
     *
     * @mbggenerated
     */
    public void setPayment(Float payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.address
     *
     * @return the value of d_house.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.address
     *
     * @param address the value for d_house.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.area
     *
     * @return the value of d_house.area
     *
     * @mbggenerated
     */
    public Float getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.area
     *
     * @param area the value for d_house.area
     *
     * @mbggenerated
     */
    public void setArea(Float area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.createtime
     *
     * @return the value of d_house.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.createtime
     *
     * @param createtime the value for d_house.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_house.updatetime
     *
     * @return the value of d_house.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_house.updatetime
     *
     * @param updatetime the value for d_house.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}