package com.entity;

import java.util.Date;

public class LoanTrackingDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    private Integer loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.upuserid
     *
     * @mbggenerated
     */
    private Integer upuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    private Integer loanamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.profit
     *
     * @mbggenerated
     */
    private Double profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.product
     *
     * @mbggenerated
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.monthcommit
     *
     * @mbggenerated
     */
    private String monthcommit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.monthfinish
     *
     * @mbggenerated
     */
    private String monthfinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.id
     *
     * @return the value of d_loan_tracking.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.id
     *
     * @param id the value for d_loan_tracking.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.realname
     *
     * @return the value of d_loan_tracking.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.realname
     *
     * @param realname the value for d_loan_tracking.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.loanid
     *
     * @return the value of d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    public Integer getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.loanid
     *
     * @param loanid the value for d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    public void setLoanid(Integer loanid) {
        this.loanid = loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.userid
     *
     * @return the value of d_loan_tracking.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.userid
     *
     * @param userid the value for d_loan_tracking.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.upuserid
     *
     * @return the value of d_loan_tracking.upuserid
     *
     * @mbggenerated
     */
    public Integer getUpuserid() {
        return upuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.upuserid
     *
     * @param upuserid the value for d_loan_tracking.upuserid
     *
     * @mbggenerated
     */
    public void setUpuserid(Integer upuserid) {
        this.upuserid = upuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.loanamount
     *
     * @return the value of d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    public Integer getLoanamount() {
        return loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.loanamount
     *
     * @param loanamount the value for d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    public void setLoanamount(Integer loanamount) {
        this.loanamount = loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.profit
     *
     * @return the value of d_loan_tracking.profit
     *
     * @mbggenerated
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.profit
     *
     * @param profit the value for d_loan_tracking.profit
     *
     * @mbggenerated
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.product
     *
     * @return the value of d_loan_tracking.product
     *
     * @mbggenerated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.product
     *
     * @param product the value for d_loan_tracking.product
     *
     * @mbggenerated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.monthcommit
     *
     * @return the value of d_loan_tracking.monthcommit
     *
     * @mbggenerated
     */
    public String getMonthcommit() {
        return monthcommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.monthcommit
     *
     * @param monthcommit the value for d_loan_tracking.monthcommit
     *
     * @mbggenerated
     */
    public void setMonthcommit(String monthcommit) {
        this.monthcommit = monthcommit == null ? null : monthcommit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.monthfinish
     *
     * @return the value of d_loan_tracking.monthfinish
     *
     * @mbggenerated
     */
    public String getMonthfinish() {
        return monthfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.monthfinish
     *
     * @param monthfinish the value for d_loan_tracking.monthfinish
     *
     * @mbggenerated
     */
    public void setMonthfinish(String monthfinish) {
        this.monthfinish = monthfinish == null ? null : monthfinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.status
     *
     * @return the value of d_loan_tracking.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.status
     *
     * @param status the value for d_loan_tracking.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.createtime
     *
     * @return the value of d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.createtime
     *
     * @param createtime the value for d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.updatetime
     *
     * @return the value of d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.updatetime
     *
     * @param updatetime the value for d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}