package com.entity;

import java.util.Date;

public class LoanStatisticDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.loanamountTotal
     *
     * @mbggenerated
     */
    private Integer loanamounttotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.profitTotal
     *
     * @mbggenerated
     */
    private Double profittotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.finish
     *
     * @mbggenerated
     */
    private Integer finish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.month
     *
     * @mbggenerated
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.commit
     *
     * @mbggenerated
     */
    private Integer commit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_statistic.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.id
     *
     * @return the value of d_loan_statistic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.id
     *
     * @param id the value for d_loan_statistic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.userid
     *
     * @return the value of d_loan_statistic.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.userid
     *
     * @param userid the value for d_loan_statistic.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.loanamountTotal
     *
     * @return the value of d_loan_statistic.loanamountTotal
     *
     * @mbggenerated
     */
    public Integer getLoanamounttotal() {
        return loanamounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.loanamountTotal
     *
     * @param loanamounttotal the value for d_loan_statistic.loanamountTotal
     *
     * @mbggenerated
     */
    public void setLoanamounttotal(Integer loanamounttotal) {
        this.loanamounttotal = loanamounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.profitTotal
     *
     * @return the value of d_loan_statistic.profitTotal
     *
     * @mbggenerated
     */
    public Double getProfittotal() {
        return profittotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.profitTotal
     *
     * @param profittotal the value for d_loan_statistic.profitTotal
     *
     * @mbggenerated
     */
    public void setProfittotal(Double profittotal) {
        this.profittotal = profittotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.finish
     *
     * @return the value of d_loan_statistic.finish
     *
     * @mbggenerated
     */
    public Integer getFinish() {
        return finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.finish
     *
     * @param finish the value for d_loan_statistic.finish
     *
     * @mbggenerated
     */
    public void setFinish(Integer finish) {
        this.finish = finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.month
     *
     * @return the value of d_loan_statistic.month
     *
     * @mbggenerated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.month
     *
     * @param month the value for d_loan_statistic.month
     *
     * @mbggenerated
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.commit
     *
     * @return the value of d_loan_statistic.commit
     *
     * @mbggenerated
     */
    public Integer getCommit() {
        return commit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.commit
     *
     * @param commit the value for d_loan_statistic.commit
     *
     * @mbggenerated
     */
    public void setCommit(Integer commit) {
        this.commit = commit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.status
     *
     * @return the value of d_loan_statistic.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.status
     *
     * @param status the value for d_loan_statistic.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.createtime
     *
     * @return the value of d_loan_statistic.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.createtime
     *
     * @param createtime the value for d_loan_statistic.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_statistic.updatetime
     *
     * @return the value of d_loan_statistic.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_statistic.updatetime
     *
     * @param updatetime the value for d_loan_statistic.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}