package com.entity;

import java.util.Date;

public class LoanTrackingDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    private Integer loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    private Integer loanamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.profit
     *
     * @mbggenerated
     */
    private Float profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.product
     *
     * @mbggenerated
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.acceptstatus
     *
     * @mbggenerated
     */
    private String acceptstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.approvalstatus
     *
     * @mbggenerated
     */
    private String approvalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.replystatus
     *
     * @mbggenerated
     */
    private String replystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.monitorstatus
     *
     * @mbggenerated
     */
    private String monitorstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.id
     *
     * @return the value of d_loan_tracking.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.id
     *
     * @param id the value for d_loan_tracking.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.realname
     *
     * @return the value of d_loan_tracking.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.realname
     *
     * @param realname the value for d_loan_tracking.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.loanid
     *
     * @return the value of d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    public Integer getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.loanid
     *
     * @param loanid the value for d_loan_tracking.loanid
     *
     * @mbggenerated
     */
    public void setLoanid(Integer loanid) {
        this.loanid = loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.loanamount
     *
     * @return the value of d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    public Integer getLoanamount() {
        return loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.loanamount
     *
     * @param loanamount the value for d_loan_tracking.loanamount
     *
     * @mbggenerated
     */
    public void setLoanamount(Integer loanamount) {
        this.loanamount = loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.profit
     *
     * @return the value of d_loan_tracking.profit
     *
     * @mbggenerated
     */
    public Float getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.profit
     *
     * @param profit the value for d_loan_tracking.profit
     *
     * @mbggenerated
     */
    public void setProfit(Float profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.product
     *
     * @return the value of d_loan_tracking.product
     *
     * @mbggenerated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.product
     *
     * @param product the value for d_loan_tracking.product
     *
     * @mbggenerated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.acceptstatus
     *
     * @return the value of d_loan_tracking.acceptstatus
     *
     * @mbggenerated
     */
    public String getAcceptstatus() {
        return acceptstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.acceptstatus
     *
     * @param acceptstatus the value for d_loan_tracking.acceptstatus
     *
     * @mbggenerated
     */
    public void setAcceptstatus(String acceptstatus) {
        this.acceptstatus = acceptstatus == null ? null : acceptstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.approvalstatus
     *
     * @return the value of d_loan_tracking.approvalstatus
     *
     * @mbggenerated
     */
    public String getApprovalstatus() {
        return approvalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.approvalstatus
     *
     * @param approvalstatus the value for d_loan_tracking.approvalstatus
     *
     * @mbggenerated
     */
    public void setApprovalstatus(String approvalstatus) {
        this.approvalstatus = approvalstatus == null ? null : approvalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.replystatus
     *
     * @return the value of d_loan_tracking.replystatus
     *
     * @mbggenerated
     */
    public String getReplystatus() {
        return replystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.replystatus
     *
     * @param replystatus the value for d_loan_tracking.replystatus
     *
     * @mbggenerated
     */
    public void setReplystatus(String replystatus) {
        this.replystatus = replystatus == null ? null : replystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.monitorstatus
     *
     * @return the value of d_loan_tracking.monitorstatus
     *
     * @mbggenerated
     */
    public String getMonitorstatus() {
        return monitorstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.monitorstatus
     *
     * @param monitorstatus the value for d_loan_tracking.monitorstatus
     *
     * @mbggenerated
     */
    public void setMonitorstatus(String monitorstatus) {
        this.monitorstatus = monitorstatus == null ? null : monitorstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.status
     *
     * @return the value of d_loan_tracking.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.status
     *
     * @param status the value for d_loan_tracking.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.createtime
     *
     * @return the value of d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.createtime
     *
     * @param createtime the value for d_loan_tracking.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_loan_tracking.updatetime
     *
     * @return the value of d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_loan_tracking.updatetime
     *
     * @param updatetime the value for d_loan_tracking.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}