package com.entity;

import java.util.Date;

public class MonitorDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.paymethod
     *
     * @mbggenerated
     */
    private String paymethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.payamount
     *
     * @mbggenerated
     */
    private Double payamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.paydate
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.endofbusiness
     *
     * @mbggenerated
     */
    private Date endofbusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.id
     *
     * @return the value of d_monitor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.id
     *
     * @param id the value for d_monitor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.paymethod
     *
     * @return the value of d_monitor.paymethod
     *
     * @mbggenerated
     */
    public String getPaymethod() {
        return paymethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.paymethod
     *
     * @param paymethod the value for d_monitor.paymethod
     *
     * @mbggenerated
     */
    public void setPaymethod(String paymethod) {
        this.paymethod = paymethod == null ? null : paymethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.payamount
     *
     * @return the value of d_monitor.payamount
     *
     * @mbggenerated
     */
    public Double getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.payamount
     *
     * @param payamount the value for d_monitor.payamount
     *
     * @mbggenerated
     */
    public void setPayamount(Double payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.paydate
     *
     * @return the value of d_monitor.paydate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.paydate
     *
     * @param paydate the value for d_monitor.paydate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.endofbusiness
     *
     * @return the value of d_monitor.endofbusiness
     *
     * @mbggenerated
     */
    public Date getEndofbusiness() {
        return endofbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.endofbusiness
     *
     * @param endofbusiness the value for d_monitor.endofbusiness
     *
     * @mbggenerated
     */
    public void setEndofbusiness(Date endofbusiness) {
        this.endofbusiness = endofbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.status
     *
     * @return the value of d_monitor.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.status
     *
     * @param status the value for d_monitor.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.createtime
     *
     * @return the value of d_monitor.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.createtime
     *
     * @param createtime the value for d_monitor.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_monitor.updatetime
     *
     * @return the value of d_monitor.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_monitor.updatetime
     *
     * @param updatetime the value for d_monitor.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}