package com.entity;

public class ServiceDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_service.serviceName
     *
     * @mbggenerated
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_service.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_service.id
     *
     * @return the value of d_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_service.id
     *
     * @param id the value for d_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_service.serviceName
     *
     * @return the value of d_service.serviceName
     *
     * @mbggenerated
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_service.serviceName
     *
     * @param servicename the value for d_service.serviceName
     *
     * @mbggenerated
     */
    public void setServicename(String servicename) {
        this.servicename = servicename == null ? null : servicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_service.password
     *
     * @return the value of d_service.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_service.password
     *
     * @param password the value for d_service.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}