package com.entity;

import java.util.Date;

public class UserIncomeDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.income
     *
     * @mbggenerated
     */
    private Double income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.upincome
     *
     * @mbggenerated
     */
    private Double upincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.creattime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user_income.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.id
     *
     * @return the value of d_user_income.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.id
     *
     * @param id the value for d_user_income.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.userid
     *
     * @return the value of d_user_income.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.userid
     *
     * @param userid the value for d_user_income.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.income
     *
     * @return the value of d_user_income.income
     *
     * @mbggenerated
     */
    public Double getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.income
     *
     * @param income the value for d_user_income.income
     *
     * @mbggenerated
     */
    public void setIncome(Double income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.upincome
     *
     * @return the value of d_user_income.upincome
     *
     * @mbggenerated
     */
    public Double getUpincome() {
        return upincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.upincome
     *
     * @param upincome the value for d_user_income.upincome
     *
     * @mbggenerated
     */
    public void setUpincome(Double upincome) {
        this.upincome = upincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.status
     *
     * @return the value of d_user_income.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.status
     *
     * @param status the value for d_user_income.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.creattime
     *
     * @return the value of d_user_income.creattime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.creattime
     *
     * @param creattime the value for d_user_income.creattime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user_income.updatetime
     *
     * @return the value of d_user_income.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user_income.updatetime
     *
     * @param updatetime the value for d_user_income.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}