package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VehicleDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public VehicleDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andTypeofcarIsNull() {
            addCriterion("typeOfCar is null");
            return (Criteria) this;
        }

        public Criteria andTypeofcarIsNotNull() {
            addCriterion("typeOfCar is not null");
            return (Criteria) this;
        }

        public Criteria andTypeofcarEqualTo(String value) {
            addCriterion("typeOfCar =", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarNotEqualTo(String value) {
            addCriterion("typeOfCar <>", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarGreaterThan(String value) {
            addCriterion("typeOfCar >", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarGreaterThanOrEqualTo(String value) {
            addCriterion("typeOfCar >=", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarLessThan(String value) {
            addCriterion("typeOfCar <", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarLessThanOrEqualTo(String value) {
            addCriterion("typeOfCar <=", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarLike(String value) {
            addCriterion("typeOfCar like", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarNotLike(String value) {
            addCriterion("typeOfCar not like", value, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarIn(List<String> values) {
            addCriterion("typeOfCar in", values, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarNotIn(List<String> values) {
            addCriterion("typeOfCar not in", values, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarBetween(String value1, String value2) {
            addCriterion("typeOfCar between", value1, value2, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andTypeofcarNotBetween(String value1, String value2) {
            addCriterion("typeOfCar not between", value1, value2, "typeofcar");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleIsNull() {
            addCriterion("natureOfVehicle is null");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleIsNotNull() {
            addCriterion("natureOfVehicle is not null");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleEqualTo(String value) {
            addCriterion("natureOfVehicle =", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleNotEqualTo(String value) {
            addCriterion("natureOfVehicle <>", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleGreaterThan(String value) {
            addCriterion("natureOfVehicle >", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleGreaterThanOrEqualTo(String value) {
            addCriterion("natureOfVehicle >=", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleLessThan(String value) {
            addCriterion("natureOfVehicle <", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleLessThanOrEqualTo(String value) {
            addCriterion("natureOfVehicle <=", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleLike(String value) {
            addCriterion("natureOfVehicle like", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleNotLike(String value) {
            addCriterion("natureOfVehicle not like", value, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleIn(List<String> values) {
            addCriterion("natureOfVehicle in", values, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleNotIn(List<String> values) {
            addCriterion("natureOfVehicle not in", values, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleBetween(String value1, String value2) {
            addCriterion("natureOfVehicle between", value1, value2, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andNatureofvehicleNotBetween(String value1, String value2) {
            addCriterion("natureOfVehicle not between", value1, value2, "natureofvehicle");
            return (Criteria) this;
        }

        public Criteria andFullcarIsNull() {
            addCriterion("fullCar is null");
            return (Criteria) this;
        }

        public Criteria andFullcarIsNotNull() {
            addCriterion("fullCar is not null");
            return (Criteria) this;
        }

        public Criteria andFullcarEqualTo(String value) {
            addCriterion("fullCar =", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarNotEqualTo(String value) {
            addCriterion("fullCar <>", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarGreaterThan(String value) {
            addCriterion("fullCar >", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarGreaterThanOrEqualTo(String value) {
            addCriterion("fullCar >=", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarLessThan(String value) {
            addCriterion("fullCar <", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarLessThanOrEqualTo(String value) {
            addCriterion("fullCar <=", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarLike(String value) {
            addCriterion("fullCar like", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarNotLike(String value) {
            addCriterion("fullCar not like", value, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarIn(List<String> values) {
            addCriterion("fullCar in", values, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarNotIn(List<String> values) {
            addCriterion("fullCar not in", values, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarBetween(String value1, String value2) {
            addCriterion("fullCar between", value1, value2, "fullcar");
            return (Criteria) this;
        }

        public Criteria andFullcarNotBetween(String value1, String value2) {
            addCriterion("fullCar not between", value1, value2, "fullcar");
            return (Criteria) this;
        }

        public Criteria andMortgageIsNull() {
            addCriterion("mortgage is null");
            return (Criteria) this;
        }

        public Criteria andMortgageIsNotNull() {
            addCriterion("mortgage is not null");
            return (Criteria) this;
        }

        public Criteria andMortgageEqualTo(String value) {
            addCriterion("mortgage =", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageNotEqualTo(String value) {
            addCriterion("mortgage <>", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageGreaterThan(String value) {
            addCriterion("mortgage >", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageGreaterThanOrEqualTo(String value) {
            addCriterion("mortgage >=", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageLessThan(String value) {
            addCriterion("mortgage <", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageLessThanOrEqualTo(String value) {
            addCriterion("mortgage <=", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageLike(String value) {
            addCriterion("mortgage like", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageNotLike(String value) {
            addCriterion("mortgage not like", value, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageIn(List<String> values) {
            addCriterion("mortgage in", values, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageNotIn(List<String> values) {
            addCriterion("mortgage not in", values, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageBetween(String value1, String value2) {
            addCriterion("mortgage between", value1, value2, "mortgage");
            return (Criteria) this;
        }

        public Criteria andMortgageNotBetween(String value1, String value2) {
            addCriterion("mortgage not between", value1, value2, "mortgage");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_vehicle
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_vehicle
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}