package com.entity;

import java.util.Date;

public class VehicleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.typeOfCar
     *
     * @mbggenerated
     */
    private String typeofcar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.natureOfVehicle
     *
     * @mbggenerated
     */
    private String natureofvehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.fullCar
     *
     * @mbggenerated
     */
    private String fullcar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.mortgage
     *
     * @mbggenerated
     */
    private String mortgage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_vehicle.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.id
     *
     * @return the value of d_vehicle.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.id
     *
     * @param id the value for d_vehicle.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.userid
     *
     * @return the value of d_vehicle.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.userid
     *
     * @param userid the value for d_vehicle.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.typeOfCar
     *
     * @return the value of d_vehicle.typeOfCar
     *
     * @mbggenerated
     */
    public String getTypeofcar() {
        return typeofcar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.typeOfCar
     *
     * @param typeofcar the value for d_vehicle.typeOfCar
     *
     * @mbggenerated
     */
    public void setTypeofcar(String typeofcar) {
        this.typeofcar = typeofcar == null ? null : typeofcar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.natureOfVehicle
     *
     * @return the value of d_vehicle.natureOfVehicle
     *
     * @mbggenerated
     */
    public String getNatureofvehicle() {
        return natureofvehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.natureOfVehicle
     *
     * @param natureofvehicle the value for d_vehicle.natureOfVehicle
     *
     * @mbggenerated
     */
    public void setNatureofvehicle(String natureofvehicle) {
        this.natureofvehicle = natureofvehicle == null ? null : natureofvehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.fullCar
     *
     * @return the value of d_vehicle.fullCar
     *
     * @mbggenerated
     */
    public String getFullcar() {
        return fullcar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.fullCar
     *
     * @param fullcar the value for d_vehicle.fullCar
     *
     * @mbggenerated
     */
    public void setFullcar(String fullcar) {
        this.fullcar = fullcar == null ? null : fullcar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.mortgage
     *
     * @return the value of d_vehicle.mortgage
     *
     * @mbggenerated
     */
    public String getMortgage() {
        return mortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.mortgage
     *
     * @param mortgage the value for d_vehicle.mortgage
     *
     * @mbggenerated
     */
    public void setMortgage(String mortgage) {
        this.mortgage = mortgage == null ? null : mortgage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.status
     *
     * @return the value of d_vehicle.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.status
     *
     * @param status the value for d_vehicle.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.createtime
     *
     * @return the value of d_vehicle.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.createtime
     *
     * @param createtime the value for d_vehicle.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_vehicle.updatetime
     *
     * @return the value of d_vehicle.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_vehicle.updatetime
     *
     * @param updatetime the value for d_vehicle.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}