package com.entityConvert;

/**
 * Created by sa on 2017-06-19.
 */
public class MonitorDOConvert {

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.loanid
     *
     * @mbggenerated
     */
    private Integer loanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.paymethod
     *
     * @mbggenerated
     */
    private String paymethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.payamount
     *
     * @mbggenerated
     */
    private Double payamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.paydate
     *
     * @mbggenerated
     */
    private String paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.endofbusiness
     *
     * @mbggenerated
     */
    private String endofbusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_monitor.updatetime
     *
     * @mbggenerated
     */
    private String updatetime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLoanid() {
        return loanid;
    }

    public void setLoanid(Integer loanid) {
        this.loanid = loanid;
    }

    public String getPaymethod() {
        return paymethod;
    }

    public void setPaymethod(String paymethod) {
        this.paymethod = paymethod;
    }

    public Double getPayamount() {
        return payamount;
    }

    public void setPayamount(Double payamount) {
        this.payamount = payamount;
    }

    public String getPaydate() {
        return paydate;
    }

    public void setPaydate(String paydate) {
        this.paydate = paydate;
    }

    public String getEndofbusiness() {
        return endofbusiness;
    }

    public void setEndofbusiness(String endofbusiness) {
        this.endofbusiness = endofbusiness;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}
