package com.mapper;

import com.entity.AnnouncementDO;
import com.entity.AnnouncementDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnnouncementDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int countByExample(AnnouncementDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int deleteByExample(AnnouncementDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int insert(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int insertSelective(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    List<AnnouncementDO> selectByExample(AnnouncementDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    AnnouncementDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnnouncementDO record, @Param("example") AnnouncementDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnnouncementDO record, @Param("example") AnnouncementDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_announcement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnnouncementDO record);
}