package com.mapper;

import com.entity.ApprovalDO;
import com.entity.ApprovalDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int countByExample(ApprovalDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int deleteByExample(ApprovalDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int insert(ApprovalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int insertSelective(ApprovalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    List<ApprovalDO> selectByExample(ApprovalDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApprovalDO record, @Param("example") ApprovalDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_approval
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApprovalDO record, @Param("example") ApprovalDOExample example);
}