package com.mapper;

import com.entity.AscriptionDO;
import com.entity.AscriptionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AscriptionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int countByExample(AscriptionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int deleteByExample(AscriptionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int insert(AscriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int insertSelective(AscriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    List<AscriptionDO> selectByExample(AscriptionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    AscriptionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AscriptionDO record, @Param("example") AscriptionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AscriptionDO record, @Param("example") AscriptionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AscriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_ascription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AscriptionDO record);
}