package com.mapper;

import com.entity.CreditCardDO;
import com.entity.CreditCardDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditCardDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int countByExample(CreditCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int deleteByExample(CreditCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int insert(CreditCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int insertSelective(CreditCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    List<CreditCardDO> selectByExample(CreditCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    CreditCardDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CreditCardDO record, @Param("example") CreditCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CreditCardDO record, @Param("example") CreditCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_creditcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditCardDO record);
}