package com.mapper;

import com.entity.LoanTrackingDO;
import com.entity.LoanTrackingDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanTrackingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int countByExample(LoanTrackingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int deleteByExample(LoanTrackingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int insert(LoanTrackingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int insertSelective(LoanTrackingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    List<LoanTrackingDO> selectByExample(LoanTrackingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    LoanTrackingDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoanTrackingDO record, @Param("example") LoanTrackingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoanTrackingDO record, @Param("example") LoanTrackingDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoanTrackingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_loan_tracking
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoanTrackingDO record);
}