package com.mapper;

import com.entity.ServiceDO;
import com.entity.ServiceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int countByExample(ServiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int deleteByExample(ServiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int insert(ServiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int insertSelective(ServiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    List<ServiceDO> selectByExample(ServiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    ServiceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ServiceDO record, @Param("example") ServiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ServiceDO record, @Param("example") ServiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ServiceDO record);
}