package com.mapper;

import com.entity.VUserIncomeDO;
import com.entity.VUserIncomeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VUserIncomeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int countByExample(VUserIncomeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int deleteByExample(VUserIncomeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int insert(VUserIncomeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int insertSelective(VUserIncomeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    List<VUserIncomeDO> selectByExample(VUserIncomeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VUserIncomeDO record, @Param("example") VUserIncomeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_income
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VUserIncomeDO record, @Param("example") VUserIncomeDOExample example);
}